### ISSUE TITLE
Export Team Event Data

### ISSUE THREAD

**Issue by HALFxAxHEART** [FIRSTinMI/FTA-Buddy#21]
Allow a team to request all match data at the end of the event. Hosted or CSV file for debugging post event.

**Comment by Filip-Kin** [comment]
I'm not sure I want to do this, just because it's a greater risk for data leaks and really the FTA should review each match log before sharing it with the team. But I did add a CSV export button for individual logs [a242ce8](https://github.com/FIRSTinMI/FTA-Buddy/commit/a242ce8665ad08f36cfb73f6ca2b921b783e14e8)
